# frozen_string_literal: true

# AutoGmSession represents a spontaneous AI-driven adventure session.
# Uses the One Page One Shot framework for adventure structure with a chaos-driven
# random event system. Manages the full lifecycle from brainstorming
# through resolution.
class AutoGmSession < Sequel::Model
  include StatusEnum
  plugin :validation_helpers
  plugin :timestamps, update_on_create: true

  # Associations
  one_to_many :auto_gm_actions, key: :session_id
  one_to_many :auto_gm_summaries, key: :session_id

  many_to_one :starting_room, class: :Room, key: :starting_room_id
  many_to_one :current_room, class: :Room, key: :current_room_id
  many_to_one :trigger, class: :Trigger, key: :trigger_id
  many_to_one :created_by, class: :Character, key: :created_by_id
  many_to_one :current_fight, class: :Fight, key: :current_fight_id
  many_to_one :universe, class: :Universe, key: :universe_id
  many_to_one :stat_block, class: :StatBlock, key: :stat_block_id

  # Status constants
  status_enum :status, %w[gathering sketching inciting running combat climax resolved abandoned]
  RESOLUTION_TYPES = %w[success failure abandoned timeout].freeze

  def validate
    super
    validates_presence [:starting_room_id, :status]
    validate_status_enum
    validates_includes RESOLUTION_TYPES, :resolution_type if resolution_type
    validates_integer :chaos_level if chaos_level
  end

  def before_create
    super
    self.status ||= 'gathering'
    self.chaos_level ||= GameConfig::AutoGm::CHAOS[:default]
    self.current_stage ||= 0
    self.current_room_id ||= starting_room_id
    self.participant_ids ||= Sequel.pg_array([], :integer)
    self.location_ids_used ||= Sequel.pg_array([], :integer)
  end

  # ========================================
  # Status Checks
  # ========================================

  # Note: simple predicates (gathering?, sketching?, etc.) are auto-generated by StatusEnum
  # combat? is auto-generated; in_combat? is an alias
  def in_combat?
    combat?
  end

  def active?
    %w[gathering sketching inciting running combat climax].include?(status)
  end

  def gm_can_act?
    %w[running climax].include?(status)
  end

  # ========================================
  # Participant Management
  # ========================================

  # Get CharacterInstance objects for all participants
  # @return [Array<CharacterInstance>]
  def participant_instances
    return [] if participant_ids.nil? || participant_ids.empty?

    # Convert PG array to Ruby array for proper query
    ids = participant_ids.to_a
    CharacterInstance.where(id: ids).all
  end

  # Get Character objects for all participants
  # @return [Array<Character>]
  def participant_characters
    participant_instances.map(&:character).compact
  end

  # Add a participant to the session
  # @param char_instance [CharacterInstance]
  def add_participant!(char_instance)
    current_ids = (participant_ids || []).to_a
    return if current_ids.include?(char_instance.id)

    update(participant_ids: Sequel.pg_array(current_ids + [char_instance.id]))
  end

  # Remove a participant from the session
  # @param char_instance [CharacterInstance]
  def remove_participant!(char_instance)
    current_ids = (participant_ids || []).to_a
    return unless current_ids.include?(char_instance.id)

    update(participant_ids: Sequel.pg_array(current_ids - [char_instance.id]))
  end

  # ========================================
  # Sketch Access
  # ========================================

  # Get the adventure title from sketch
  # @return [String, nil]
  def title
    sketch&.dig('title')
  end

  # Get the mission type from sketch
  # @return [String, nil]
  def mission_type
    sketch&.dig('mission', 'type')
  end

  # Get the mission objective from sketch
  # @return [String, nil]
  def mission_objective
    sketch&.dig('mission', 'objective')
  end

  # Get secrets that haven't been revealed yet
  # @return [Array<String>]
  def unrevealed_secrets
    all_secrets = sketch&.dig('secrets_twists', 'secrets') || []
    revealed = world_state&.dig('secrets_revealed') || []
    all_secrets - revealed
  end

  # Get the structure stages
  # @return [Array<Hash>]
  def stages
    sketch&.dig('structure', 'stages') || []
  end

  # Get current stage info
  # @return [Hash, nil]
  def current_stage_info
    stages[current_stage]
  end

  # Get total number of stages
  # @return [Integer]
  def total_stages
    stages.length
  end

  # Check if using countdown structure
  # @return [Boolean]
  def countdown_structure?
    sketch&.dig('structure', 'type') == 'countdown'
  end

  # ========================================
  # Stat Integration
  # ========================================

  # Get available stats from the session's stat block
  # @return [Array<Hash>] [{ id:, name:, abbreviation:, category: }, ...]
  def available_stats
    return [] unless stat_block_id

    sb = stat_block
    return [] unless sb

    sb.stats.map do |s|
      { id: s.id, name: s.name, abbreviation: s.abbreviation, category: s.stat_category }
    end
  end

  # Get stat names as a comma-separated string for prompts
  # @return [String]
  def stat_names_for_prompt
    names = available_stats.map { |s| s[:name] }
    names.any? ? names.join(', ') : 'No stats available'
  end

  # Resolve a stat name (from LLM output) to a Stat record
  # Tries exact name match, then case-insensitive, then abbreviation
  # @param name [String] stat name from LLM (e.g. "Strength", "STR")
  # @return [Stat, nil]
  def resolve_stat_by_name(name)
    return nil unless stat_block_id && name

    sb = stat_block
    return nil unless sb

    clean = name.to_s.strip
    stats = sb.stats

    # Exact name match
    stats.find { |s| s.name == clean } ||
      # Case-insensitive name match
      stats.find { |s| s.name.downcase == clean.downcase } ||
      # Abbreviation match (case-insensitive)
      stats.find { |s| s.abbreviation&.downcase == clean.downcase }
  end

  # Get stat values for a character instance
  # @param character_instance [CharacterInstance]
  # @return [Array<Hash>] [{ name:, abbreviation:, value: }, ...]
  def stat_values_for(character_instance)
    return [] unless stat_block_id

    character_instance.character_stats.filter_map do |cs|
      next unless cs.stat

      { name: cs.stat.name, abbreviation: cs.stat.abbreviation, value: cs.current_value }
    end
  end

  # ========================================
  # Chaos Management
  # ========================================

  # Increase chaos level (PCs lost control)
  def increase_chaos!
    new_level = [chaos_level + 1, GameConfig::AutoGm::CHAOS[:maximum]].min
    update(chaos_level: new_level) if new_level != chaos_level
  end

  # Decrease chaos level (PCs took control)
  def decrease_chaos!
    new_level = [chaos_level - 1, GameConfig::AutoGm::CHAOS[:minimum]].max
    update(chaos_level: new_level) if new_level != chaos_level
  end

  # Adjust chaos level by a specific amount
  # @param amount [Integer] positive to increase, negative to decrease
  def adjust_chaos!(amount)
    new_level = [[chaos_level + amount, GameConfig::AutoGm::CHAOS[:minimum]].max, GameConfig::AutoGm::CHAOS[:maximum]].min
    update(chaos_level: new_level) if new_level != chaos_level
  end

  # Check if random event should trigger (doubles rule)
  # @param roll [Integer] 1-100 roll
  # @return [Boolean]
  def random_event_triggered?(roll)
    tens = roll / 10
    ones = roll % 10
    tens == ones && tens <= chaos_level
  end

  # ========================================
  # Stage Progression
  # ========================================

  # Advance to the next stage
  # @return [Boolean] true if advanced, false if already at end
  def advance_stage!
    return false if current_stage >= total_stages - 1

    new_stage = current_stage + 1
    update(current_stage: new_stage)

    # Update countdown if applicable
    decrement_countdown! if countdown_structure? && countdown

    true
  end

  # Decrement the countdown timer
  def decrement_countdown!
    return unless countdown && countdown.positive?

    update(countdown: countdown - 1)
  end

  # ========================================
  # World State Management
  # ========================================

  # Track a spawned NPC
  # @param npc_name [String]
  def track_npc_spawned!(npc_name)
    # Must deep-dup to avoid Sequel JSONB dirty-tracking issue
    state = JSON.parse((world_state || {}).to_json)
    state['npcs_spawned'] ||= []
    state['npcs_spawned'] << npc_name
    update(world_state: Sequel.pg_jsonb_wrap(state))
  end

  # Track a spawned item
  # @param item_desc [String]
  def track_item_spawned!(item_desc)
    # Must deep-dup to avoid Sequel JSONB dirty-tracking issue
    state = JSON.parse((world_state || {}).to_json)
    state['items_appeared'] ||= []
    state['items_appeared'] << item_desc
    update(world_state: Sequel.pg_jsonb_wrap(state))
  end

  # Track a revealed secret
  # @param secret [String]
  def track_secret_revealed!(secret)
    # Must deep-dup to avoid Sequel JSONB dirty-tracking issue
    state = JSON.parse((world_state || {}).to_json)
    state['secrets_revealed'] ||= []
    state['secrets_revealed'] << secret
    update(world_state: Sequel.pg_jsonb_wrap(state))
  end

  # Track a disposition change
  # @param npc_name [String]
  # @param change [String] e.g., "hostile->friendly"
  def track_disposition_change!(npc_name, change)
    # Must deep-dup to avoid Sequel JSONB dirty-tracking issue
    state = JSON.parse((world_state || {}).to_json)
    state['disposition_changes'] ||= []
    state['disposition_changes'] << { npc: npc_name, change: change }
    update(world_state: Sequel.pg_jsonb_wrap(state))
  end

  # ========================================
  # Location Management
  # ========================================

  # Add a location to the used list
  # @param location_id [Integer]
  def use_location!(location_id)
    current_locs = (location_ids_used || []).to_a
    return if current_locs.include?(location_id)

    update(location_ids_used: Sequel.pg_array(current_locs + [location_id]))
  end

  # Move to a different room
  # @param room [Room]
  def move_to!(room)
    update(current_room_id: room.id)
    use_location!(room.location_id) if room.location_id
  end

  # ========================================
  # Combat Integration
  # ========================================

  # Enter combat mode
  # @param fight [Fight]
  def enter_combat!(fight)
    update(status: 'combat', current_fight_id: fight.id)
  end

  # Exit combat mode and resume GM loop
  def exit_combat!
    update(status: 'running', current_fight_id: nil)
  end

  # ========================================
  # Session Lifecycle
  # ========================================

  # Start the inciting incident phase
  def start_inciting!
    update(status: 'inciting')
  end

  # Start the main GM loop
  def start_running!
    update(status: 'running', started_at: Time.now)
  end

  # Enter the climax phase
  def start_climax!
    update(status: 'climax')
  end

  # Resolve the session
  # @param type [Symbol] :success, :failure, :abandoned, :timeout
  def resolve!(type)
    update(
      status: 'resolved',
      resolved_at: Time.now,
      resolution_type: type.to_s
    )
  end

  # Abandon the session
  def abandon!
    update(
      status: 'abandoned',
      resolved_at: Time.now,
      resolution_type: 'abandoned'
    )
  end

  # Check if session has been inactive too long
  # @return [Boolean]
  def timed_out?
    return false unless active?

    last_activity = last_action_at || started_at || created_at
    Time.now - last_activity > (GameConfig::AutoGm::INACTIVITY_TIMEOUT_HOURS * 3600)
  end

  # Get last activity timestamp
  # @return [Time, nil]
  def last_action_at
    auto_gm_actions_dataset.max(:created_at)
  end

  # ========================================
  # Action Helpers
  # ========================================

  # Get the next sequence number for actions
  # @return [Integer]
  def next_sequence_number
    (auto_gm_actions_dataset.max(:sequence_number) || 0) + 1
  end

  # Get recent actions
  # @param limit [Integer]
  # @return [Array<AutoGmAction>]
  def recent_actions(limit: 10)
    auto_gm_actions_dataset
      .order(Sequel.desc(:sequence_number))
      .limit(limit)
      .all
      .reverse
  end

  # Get recent emits (narrative text)
  # @param limit [Integer]
  # @return [Array<String>]
  def recent_emits(limit: 10)
    auto_gm_actions_dataset
      .where(action_type: 'emit')
      .exclude(emit_text: nil)
      .order(Sequel.desc(:sequence_number))
      .limit(limit)
      .select_map(:emit_text)
      .reverse
  end

  # ========================================
  # Summary/Compression Helpers
  # ========================================

  # Get the most relevant summary for context
  # @return [String, nil]
  def current_summary
    # Prefer higher abstraction levels
    summary = auto_gm_summaries_dataset
      .order(Sequel.desc(:abstraction_level), Sequel.desc(:created_at))
      .first
    summary&.content
  end

  # Get summaries at a specific level
  # @param level [Integer] 1-4
  # @return [Array<AutoGmSummary>]
  def summaries_at_level(level)
    auto_gm_summaries_dataset
      .where(abstraction_level: level)
      .order(:created_at)
      .all
  end

  # ========================================
  # Class Methods
  # ========================================

  class << self
    # Find all active sessions
    def active
      where(status: %w[gathering sketching inciting running combat climax])
    end

    # Find sessions in a specific room
    # @param room [Room]
    def in_room(room)
      active.where(current_room_id: room.id)
    end

    # Find sessions that have timed out
    # Uses SQL query for efficiency instead of loading all into memory
    def timed_out
      timeout_cutoff = Time.now - (GameConfig::AutoGm::INACTIVITY_TIMEOUT_HOURS * 3600)
      actions = AutoGmAction.table_name
      sessions = table_name
      active.where(Sequel.lit(
        "COALESCE((SELECT MAX(created_at) FROM #{actions} WHERE #{actions}.session_id = #{sessions}.id), #{sessions}.started_at, #{sessions}.created_at) < ?",
        timeout_cutoff
      ))
    end

    # Find sessions for a participant
    # @param char_instance [CharacterInstance]
    def for_participant(char_instance)
      active.where(Sequel.pg_array_op(:participant_ids).contains([char_instance.id]))
    end

    # Find sessions created by a character
    # @param character [Character]
    def created_by_character(character)
      where(created_by_id: character.id)
    end
  end
end
