# frozen_string_literal: true

# ChapterTitle stores cached chapter titles for character stories
#
# Titles can be auto-generated by LLM or default to "Chapter N"
class ChapterTitle < Sequel::Model
  plugin :timestamps
  plugin :validation_helpers

  many_to_one :character

  def validate
    super
    validates_presence [:character_id, :chapter_index, :title]
    validates_integer :chapter_index
  end

  # Get all titles for a character, ordered by chapter
  # @param character_id [Integer]
  # @return [Array<ChapterTitle>]
  def self.for_character(character_id)
    where(character_id: character_id)
      .order(:chapter_index)
      .all
  end

  # Get or create a title for a specific chapter
  # @param character_id [Integer]
  # @param chapter_index [Integer]
  # @param default_title [String]
  # @return [ChapterTitle]
  def self.find_or_create_for(character_id, chapter_index, default_title: nil)
    existing = first(character_id: character_id, chapter_index: chapter_index)
    return existing if existing

    create(
      character_id: character_id,
      chapter_index: chapter_index,
      title: default_title || "Chapter #{chapter_index + 1}"
    )
  end

  # Clear all titles for a character (used when chapter boundaries change)
  # @param character_id [Integer]
  def self.clear_for(character_id)
    where(character_id: character_id).delete
  end
end
