# frozen_string_literal: true

# Event represents scheduled calendar events (parties, meetings, etc.)
# RP inside events is separate from outside. Can add temporary furniture/decorations.
class Event < Sequel::Model
  include StatusEnum
  plugin :validation_helpers
  plugin :timestamps

  many_to_one :location
  many_to_one :room
  many_to_one :organizer, class: :Character
  one_to_many :event_attendees
  one_to_many :event_room_states
  one_to_many :event_decorations
  one_to_many :event_places

  EVENT_TYPES = %w[party meeting competition concert ceremony private public].freeze
  status_enum :status, %w[scheduled active completed cancelled]
  LOG_VISIBILITY = %w[public attendees organizer].freeze

  def validate
    super
    validates_presence [:name, :event_type, :starts_at]
    validates_max_length 200, :name
    validates_includes EVENT_TYPES, :event_type
    validate_status_enum
    validates_includes LOG_VISIBILITY, :logs_visible_to if logs_visible_to
  end

  def before_save
    super
    self.status ||= 'scheduled'
    self.is_public = true if is_public.nil?
    self.logs_visible_to ||= 'public'
    # Sync title and name - title is required by db, name is used by model
    self.title ||= name
    self.name ||= title
  end

  # Note: simple predicates (scheduled?, active?, completed?, cancelled?) are auto-generated by StatusEnum

  def start!
    update(status: 'active', started_at: Time.now)
  end

  def complete!
    update(status: 'completed', ended_at: Time.now)
  end

  def cancel!
    update(status: 'cancelled')
  end

  def upcoming?
    scheduled? && starts_at > Time.now
  end

  def in_progress?
    active? || (scheduled? && starts_at <= Time.now && (!ends_at || ends_at > Time.now))
  end

  def attendees
    event_attendees_dataset.eager(:character)
  end

  def add_attendee(character, rsvp: 'yes')
    EventAttendee.find_or_create(event_id: id, character_id: character.id) do |a|
      a.status = rsvp
    end
  end

  def attending?(character)
    return false unless character

    EventAttendee.where(event_id: id, character_id: character.id, status: 'yes').any?
  end

  def attendee_count
    event_attendees_dataset.where(status: 'yes').count
  end

  # Get all character instances currently in this event
  def characters_in_event
    CharacterInstance.where(in_event_id: id)
  end

  # End the event and remove all characters from it
  def end_for_all!
    characters_in_event.update(
      in_event_id: nil,
      event_camera: false,
      spotlight_remaining: nil
    )
    cleanup_temporary_content!
    complete!
  end

  # Snapshot the room state when event starts
  def snapshot_room!(the_room = nil)
    target_room = the_room || room
    return unless target_room

    EventRoomState.snapshot!(self, target_room)
  end

  # Get the room state for this event
  def room_state_for(the_room)
    EventRoomState.first(event_id: id, room_id: the_room.id)
  end

  # Cleanup all temporary content when event ends
  def cleanup_temporary_content!
    EventDecoration.cleanup_event!(self)
    EventPlace.cleanup_event!(self)
    # Room states are kept for historical reference
  end

  # Get decorations for a specific room during this event
  def decorations_for(the_room)
    EventDecoration.for_event_room(self, the_room)
  end

  # Get places for a specific room during this event
  def places_for(the_room)
    EventPlace.for_event_room(self, the_room)
  end

  # Check if a character can view the logs for this event
  def can_view_logs?(character)
    return true if logs_visible_to == 'public'
    return true if organizer_id == character&.id

    case logs_visible_to
    when 'attendees'
      attending?(character) || was_attending?(character)
    when 'organizer'
      organizer_id == character&.id
    else
      true
    end
  end

  # Check if character was ever an attendee (for completed events)
  def was_attending?(character)
    return false unless character

    EventAttendee.where(event_id: id, character_id: character.id).any?
  end

  # Get RP logs for this event
  def rp_logs
    RpLog.where(event_id: id).order(:created_at)
  end

  # Class methods for calendar queries
  def self.upcoming(limit: 10)
    where { starts_at > Time.now }
      .where(status: %w[scheduled active])
      .order(:starts_at)
      .limit(limit)
  end

  def self.public_upcoming(limit: 10)
    upcoming(limit: limit).where(is_public: true)
  end

  def self.for_character(character, limit: 10)
    ids = EventAttendee.where(character_id: character.id).select(:event_id)
    where(Sequel.or(
      id: ids,
      organizer_id: character.id
    ))
      .where(status: %w[scheduled active])
      .order(:starts_at)
      .limit(limit)
  end

  def self.at_location(location, limit: 10)
    where(location_id: location.id)
      .where { starts_at > Time.now }
      .where(status: %w[scheduled active])
      .order(:starts_at)
      .limit(limit)
  end

  def self.at_room(the_room, limit: 10)
    where(room_id: the_room.id)
      .where { starts_at > Time.now }
      .where(status: %w[scheduled active])
      .order(:starts_at)
      .limit(limit)
  end

  def self.active_events
    where(status: 'active')
  end

  # Find active event at a room
  def self.active_at_room(the_room)
    active_events.where(room_id: the_room.id).first
  end

  # Find an active event where the character has organizer or staff authority
  # @param char [Character] The character to check
  # @param loc [Room] The location (room) to check
  # @return [Event, nil] The event or nil if none found
  def self.find_controllable_by(char, loc)
    return nil unless loc

    where(status: 'active')
      .where(Sequel.or(room_id: loc.id, location_id: loc.location_id))
      .all
      .find { |event| event.controllable_by?(char) }
  end

  # Check if a character can control this event (is organizer or staff)
  # @param char [Character] The character to check
  # @return [Boolean]
  def controllable_by?(char)
    return false unless char

    # Organizers always have control
    return true if organizer_id == char.id

    # Check if they're staff
    attendee = EventAttendee.for_event_and_character(self, char)
    attendee&.staff? || false
  end
end
