# frozen_string_literal: true

require_relative '../app'

# Export all helpfile descriptions to a seed file format
# Run: bundle exec ruby scripts/export_helpfile_descriptions.rb

OUTPUT_FILE = File.join(__dir__, '../db/seeds/helpfile_descriptions.rb')

puts "Exporting helpfile descriptions..."

# Get all helpfiles with descriptions
helpfiles = Helpfile.exclude(description: nil)
                    .where { Sequel.lit("description != ''") }
                    .order(:command_name)
                    .all

if helpfiles.empty?
  puts "No helpfiles with descriptions found."
  exit 0
end

# Build the seed file content
content = <<~RUBY
  # frozen_string_literal: true

  # Helpfile Descriptions Seed
  # Auto-generated by scripts/export_helpfile_descriptions.rb
  # Run: bundle exec ruby db/seeds/helpfile_descriptions.rb

  puts "Seeding helpfile descriptions..."

  DESCRIPTIONS = {
RUBY

helpfiles.each do |hf|
  # Escape the description for Ruby string literal
  escaped_desc = hf.description.gsub('\\', '\\\\\\\\').gsub('"', '\\"').gsub("\n", "\\n")

  content += "    '#{hf.command_name}' => \"#{escaped_desc}\",\n"
end

content += <<~RUBY
  }.freeze

  # Update descriptions
  count = 0
  DESCRIPTIONS.each do |command_name, description|
    helpfile = Helpfile.first(command_name: command_name)
    if helpfile
      helpfile.update(description: description)
      count += 1
      print '.'
    else
      warn "\\nWarning: Helpfile not found for command '#{command_name}'"
    end
  end

  puts "\\n\\u2713 Seeded #{count} helpfile descriptions"
RUBY

# Write to file
File.write(OUTPUT_FILE, content)

puts "✓ Exported #{helpfiles.count} helpfile descriptions to:"
puts "  #{OUTPUT_FILE}"
puts ""
puts "To seed descriptions after database regeneration:"
puts "  bundle exec ruby db/seeds/helpfile_descriptions.rb"
