# frozen_string_literal: true

# Processes ability execution with AoE targeting, damage calculation,
# status effect application, and cost handling.
# Replaces hardcoded ability processing with data-driven execution.
#
# For PCs: Uses the same 2d8+willpower roll as attacks (passed in as base_roll)
# For NPCs: Can use ability-specific dice or custom NPC dice
class AbilityProcessorService
  attr_reader :actor, :ability, :primary_target, :fight, :events, :base_roll

  # @param actor [FightParticipant] who is using the ability
  # @param ability [Ability] the ability being used
  # @param primary_target [FightParticipant] the target (for enemy/ally targeted)
  # @param base_roll [DiceRollService::RollResult] pre-rolled effectiveness (for PCs, same as attack roll)
  def initialize(actor:, ability:, primary_target: nil, base_roll: nil)
    @actor = actor
    @ability = ability
    @primary_target = primary_target
    @fight = actor.fight
    @events = []
    @base_roll = base_roll
  end

  # Process the ability and return events
  # @param segment [Integer] the segment this ability is activating at
  # @return [Array<Hash>] events generated by this ability
  def process!(segment)
    return [] if actor.is_knocked_out

    # Cache active participants to avoid repeated DB queries during target resolution
    @cached_participants = fight.active_participants.all

    # Announce ability start/casting
    @events << create_event(segment, 'ability_start',
                            ability_name: ability.name,
                            ability_description: ability.description,
                            action_type: ability.action_type,
                            aoe_shape: ability.aoe_shape,
                            damage_type: ability.damage_type)

    # Resolve all targets based on AoE shape
    targets = resolve_targets

    if targets.empty?
      @events << create_event(segment, 'ability_no_target',
                              ability_name: ability.name,
                              reason: 'no valid targets')
      return @events
    end

    # Process each target
    targets.each do |target_info|
      process_target(
        target_info[:target],
        target_info[:is_primary],
        segment,
        damage_multiplier: target_info[:damage_multiplier] || 1.0,
        chain_index: target_info[:chain_index]
      )
    end

    # Apply costs to the caster
    apply_costs!

    @events
  end

  private

  # Resolve all targets based on ability configuration
  # @return [Array<Hash>] array of { target:, is_primary: }
  def resolve_targets
    case ability.aoe_shape
    when 'single'
      resolve_single_target
    when 'circle'
      resolve_circle_targets
    when 'cone'
      resolve_cone_targets
    when 'line'
      resolve_line_targets
    else
      resolve_single_target
    end
  end

  # Single target resolution - also handles chain abilities
  def resolve_single_target
    target = effective_target
    return [] unless target && !target.is_knocked_out
    return [] unless valid_target_for_ability?(target)
    return [] unless in_range_of_actor?(target)

    # Check if this ability chains to additional targets
    if ability.has_chain?
      resolve_chain_targets(target)
    else
      [{ target: target, is_primary: true }]
    end
  end

  # Resolve chain ability targets - bounces between nearby enemies
  # Each bounce reduces damage by falloff percentage
  def resolve_chain_targets(initial_target)
    chain = ability.parsed_chain_config
    max_targets = chain['max_targets'] || 3
    range_per_jump = chain['range_per_jump'] || 3
    friendly_fire = chain['friendly_fire'] == true

    targets = [{ target: initial_target, is_primary: true, chain_index: 0, damage_multiplier: 1.0 }]
    hit_ids = [initial_target.id]
    current_target = initial_target
    current_multiplier = 1.0
    falloff = chain['damage_falloff'] || 0.5

    # Find additional targets to chain to
    (max_targets - 1).times do |i|
      current_multiplier *= falloff

      # Find nearest valid target within range
      next_target = find_next_chain_target(current_target, hit_ids, range_per_jump, friendly_fire)
      break unless next_target

      targets << {
        target: next_target,
        is_primary: false,
        chain_index: i + 1,
        damage_multiplier: current_multiplier
      }
      hit_ids << next_target.id
      current_target = next_target
    end

    targets
  end

  # Find the next target for chain ability
  def find_next_chain_target(from_target, hit_ids, max_range, friendly_fire)
    candidates = @cached_participants.select do |p|
      next false if p.is_knocked_out
      next false if hit_ids.include?(p.id)
      next false if p.id == actor.id # Can't chain to self
      next false unless chain_target_allowed?(p, friendly_fire)

      distance = from_target.hex_distance_to(p)
      next false if distance.nil? # Skip if positions unknown

      # Allow distance 0 (same hex) - chain can hit multiple targets in same location
      distance >= 0 && distance <= max_range
    end

    # Return nearest candidate
    candidates.min_by { |p| from_target.hex_distance_to(p) || Float::INFINITY }
  end

  # Circle AoE centered on target (or self if self-targeted)
  def resolve_circle_targets
    center = effective_target
    return [] unless center
    return [] unless in_range_of_actor?(center)

    radius = ability.aoe_radius || 1
    targets = []

    @cached_participants.each do |p|
      next if p.is_knocked_out
      next if p.id == actor.id && ability.target_type != 'self'
      next unless valid_target_for_ability?(p, aoe_context: true)

      distance = center.hex_distance_to(p)
      next if distance.nil? || distance > radius

      targets << {
        target: p,
        is_primary: p.id == center.id
      }
    end

    targets
  end

  # Cone AoE from actor towards target
  def resolve_cone_targets
    direction_target = effective_target
    return [] unless direction_target
    return [] unless in_range_of_actor?(direction_target)
    return [] if actor.hex_x.nil? || actor.hex_y.nil?
    return [] if direction_target.hex_x.nil? || direction_target.hex_y.nil?

    length = ability.aoe_length || 3
    angle = ability.aoe_angle.to_i.nonzero? || 60
    targets = []

    # Calculate cone direction vector
    dx = direction_target.hex_x - actor.hex_x
    dy = direction_target.hex_y - actor.hex_y
    cone_direction = Math.atan2(dy, dx)
    half_angle = (angle / 2.0) * Math::PI / 180

    @cached_participants.each do |p|
      next if p.is_knocked_out
      next if p.id == actor.id # Actor not in own cone
      next unless valid_target_for_ability?(p, aoe_context: true)
      next if p.hex_x.nil? || p.hex_y.nil?

      # Check if within cone range
      distance = actor.hex_distance_to(p)
      next if distance.nil? || distance > length
      next if distance == 0 # Skip actor

      # Check if within cone angle
      pdx = p.hex_x - actor.hex_x
      pdy = p.hex_y - actor.hex_y
      p_angle = Math.atan2(pdy, pdx)
      angle_diff = (p_angle - cone_direction).abs

      # Normalize angle difference
      angle_diff = 2 * Math::PI - angle_diff if angle_diff > Math::PI

      next if angle_diff > half_angle

      targets << {
        target: p,
        is_primary: p.id == direction_target.id
      }
    end

    targets
  end

  # Line AoE from actor through target
  def resolve_line_targets
    direction_target = effective_target
    return [] unless direction_target
    return [] unless in_range_of_actor?(direction_target)
    return [] if actor.hex_x.nil? || actor.hex_y.nil?
    return [] if direction_target.hex_x.nil? || direction_target.hex_y.nil?

    length = ability.aoe_length || 5
    targets = []

    # Calculate line direction
    dx = direction_target.hex_x - actor.hex_x
    dy = direction_target.hex_y - actor.hex_y
    dist = Math.sqrt(dx * dx + dy * dy)
    return [] if dist == 0

    # Normalize direction
    ndx = dx / dist
    ndy = dy / dist

    @cached_participants.each do |p|
      next if p.is_knocked_out
      next if p.id == actor.id
      next unless valid_target_for_ability?(p, aoe_context: true)
      next if p.hex_x.nil? || p.hex_y.nil?

      # Check distance along line
      pdx = p.hex_x - actor.hex_x
      pdy = p.hex_y - actor.hex_y
      proj_length = pdx * ndx + pdy * ndy

      next if proj_length <= 0 || proj_length > length

      # Check perpendicular distance (within 0.5 hex of line)
      perp_dist = (pdx * ndy - pdy * ndx).abs
      next if perp_dist > 0.5

      targets << {
        target: p,
        is_primary: p.id == direction_target.id
      }
    end

    targets
  end

  # Get the effective target based on ability target type
  def effective_target
    case ability.target_type
    when 'self'
      actor
    when 'ally', 'enemy'
      primary_target
    else
      primary_target
    end
  end

  # Check if a participant is a valid target for this ability
  def valid_target_for_ability?(target, aoe_context: false)
    # Friendly-fire AoEs can include allies in splash if configured.
    if aoe_context && ability.has_aoe? && ability.aoe_hits_allies && ability.target_type == 'enemy'
      return target.id != actor.id
    end

    case ability.target_type
    when 'self'
      target.id == actor.id
    when 'ally'
      # Same team (placeholder - implement team logic)
      target.id == actor.id || same_team?(target)
    when 'enemy'
      target.id != actor.id && !same_team?(target)
    else
      true
    end
  end

  # Check if on same team/side as another participant
  # Uses the new side field on FightParticipant
  def same_team?(target)
    return false unless actor.respond_to?(:side) && target.respond_to?(:side)
    return false if actor.side.nil? || target.side.nil?

    actor.side == target.side
  end

  def in_range_of_actor?(target)
    return true if ability.self_targeted?

    distance = actor.hex_distance_to(target)
    return true if distance.nil?

    distance <= ability.range_in_hexes
  end

  # Process a single target
  # @param damage_multiplier [Float] for chain abilities, reduces damage per bounce
  # @param chain_index [Integer, nil] 0 = primary, 1+ = chain bounce number
  def process_target(target, is_primary, segment, damage_multiplier: 1.0, chain_index: nil)
    if ability.healing_ability?
      process_healing(target, is_primary, segment)
    else
      process_damage(target, is_primary, segment, damage_multiplier: damage_multiplier, chain_index: chain_index)
    end

    # Apply status effects from ability configuration
    apply_status_effects(target, segment)

    # Apply forced movement
    apply_forced_movement(target, segment) if ability.has_forced_movement?

    # Apply prone
    apply_prone(target, segment) if ability.applies_prone
  end

  # Process damage to a target
  # @param damage_multiplier [Float] for chain abilities, reduces damage per bounce
  # @param chain_index [Integer, nil] 0 = primary, 1+ = chain bounce number
  def process_damage(target, is_primary, segment, damage_multiplier: 1.0, chain_index: nil)
    return unless damaging_ability?

    # Check for execute mechanic first (may instant kill or multiply damage)
    execute_result = check_execute(target)
    if execute_result[:instant_kill]
      target.knockout!
      @events << create_event(segment, 'ability_execute',
                              ability_name: ability.name,
                              target_id: target.id,
                              target_name: target.character_name,
                              instant_kill: true,
                              threshold: ability.execute_threshold)
      return
    end

    # Roll base damage
    raw_damage = roll_damage

    # Apply chain damage falloff (e.g., 50% per bounce)
    if damage_multiplier < 1.0
      raw_damage = (raw_damage * damage_multiplier).to_i
    end

    # Apply execute damage multiplier if threshold met
    if execute_result[:multiplier]
      raw_damage = (raw_damage * execute_result[:multiplier]).to_i
      @events << create_event(segment, 'ability_execute_bonus',
                              ability_name: ability.name,
                              target_id: target.id,
                              target_name: target.character_name,
                              multiplier: execute_result[:multiplier])
    end

    # Apply conditional damage bonuses
    conditional_bonus = calculate_conditional_damage(target)
    raw_damage += conditional_bonus

    # Apply combo bonuses
    combo_bonus = calculate_combo_damage(target)
    raw_damage += combo_bonus

    # Track actor's attack count for conditional damage
    actor.increment_attacks!

    # Willpower defense is pre-rolled once per round in CombatResolutionService#initialize_round_state
    # and applied to cumulative damage in calculate_effective_cumulative, not per-hit here
    effective_damage = raw_damage

    # Process damage based on type configuration
    if ability.has_split_damage?
      effective_damage = process_split_damage(target, effective_damage, segment)
    else
      effective_damage = apply_damage_modifiers(target, effective_damage, ability.damage_type)
    end

    # Accumulate damage
    target.accumulate_damage!(effective_damage)

    # Apply lifesteal
    if ability.has_lifesteal?
      heal_amount = [effective_damage, ability.lifesteal_max].min
      actor.heal!(heal_amount)
      @events << create_event(segment, 'ability_lifesteal',
                              ability_name: ability.name,
                              amount: heal_amount,
                              target_id: target.id,
                              target_name: target.character_name)
    end

    @events << create_event(segment, 'ability_hit',
                            ability_name: ability.name,
                            raw_damage: raw_damage,
                            conditional_bonus: conditional_bonus > 0 ? conditional_bonus : nil,
                            combo_bonus: combo_bonus > 0 ? combo_bonus : nil,
                            effective_damage: effective_damage,
                            damage_type: ability.damage_type,
                            is_aoe: !is_primary,
                            is_chain: !chain_index.nil? && chain_index > 0,
                            chain_index: chain_index,
                            chain_damage_multiplier: damage_multiplier < 1.0 ? damage_multiplier : nil,
                            target_id: target.id,
                            target_name: target.character_name)
  end

  # Check execute mechanics
  # @return [Hash] { instant_kill: bool, multiplier: Float }
  def check_execute(target)
    return {} unless ability.has_execute?

    hp_percent = (target.current_hp.to_f / target.max_hp) * 100
    return {} unless hp_percent <= ability.execute_threshold

    effect = ability.parsed_execute_effect || {}
    {
      instant_kill: effect['instant_kill'] == true,
      multiplier: effect['damage_multiplier']&.to_f
    }
  end

  # Calculate conditional damage bonuses
  # @return [Integer] total bonus damage
  def calculate_conditional_damage(target)
    return 0 unless ability.has_conditional_damage?

    bonus = 0
    ability.parsed_conditional_damage.each do |condition|
      next unless evaluate_condition(condition, target)

      if condition['bonus_dice']
        bonus += DiceNotationService.roll(condition['bonus_dice'])
      elsif condition['bonus_damage']
        bonus += condition['bonus_damage'].to_i
      end
    end
    bonus
  end

  # Evaluate a damage condition
  def evaluate_condition(condition, target)
    case condition['condition']
    when 'target_below_50_hp'
      target.current_hp < (target.max_hp * 0.5)
    when 'target_below_25_hp'
      target.current_hp < (target.max_hp * 0.25)
    when 'target_has_status'
      StatusEffectService.has_effect?(target, condition['status'])
    when 'first_attack_of_round'
      actor.attacks_this_round.to_i.zero?
    when 'target_prone'
      StatusEffectService.is_prone?(target)
    when 'target_burning'
      StatusEffectService.has_effect?(target, 'burning')
    when 'target_poisoned'
      StatusEffectService.has_effect?(target, 'poisoned')
    when 'target_bleeding'
      StatusEffectService.has_effect?(target, 'bleeding')
    else
      false
    end
  end

  # Calculate combo damage bonuses
  # @return [Integer] bonus damage
  def calculate_combo_damage(target)
    return 0 unless ability.has_combo?

    combo = ability.parsed_combo_condition
    return 0 unless StatusEffectService.has_effect?(target, combo['requires_status'])

    bonus = combo['bonus_dice'] ? DiceNotationService.roll(combo['bonus_dice']) : 0

    # Consume the status effect if configured
    if combo['consumes_status']
      StatusEffectService.remove_effect(target, combo['requires_status'])
    end

    bonus
  end

  # Process split damage types
  # @return [Integer] total damage after modifiers
  def process_split_damage(target, total_damage, segment)
    final_damage = 0

    ability.parsed_damage_types.each do |split|
      damage_type = split['type']
      percent = split['value'].to_s.gsub('%', '').to_f / 100
      portion = (total_damage * percent).to_i

      # Apply damage modifiers for this type
      modified = apply_damage_modifiers(target, portion, damage_type)
      final_damage += modified

      @events << create_event(segment, 'ability_split_damage',
                              ability_name: ability.name,
                              damage_type: damage_type,
                              portion: portion,
                              modified: modified,
                              target_id: target.id,
                              target_name: target.character_name)
    end

    final_damage
  end

  # Apply damage modifiers (resistance/vulnerability/shields)
  def apply_damage_modifiers(target, damage, damage_type)
    # Skip modifiers if ability bypasses resistances
    unless ability.bypasses_resistances
      # Apply vulnerability/resistance multiplier
      multiplier = StatusEffectService.damage_type_multiplier(target, damage_type)
      damage = (damage * multiplier).to_i
    end

    # Apply flat damage reduction
    reduction = StatusEffectService.flat_damage_reduction(target, damage_type)
    damage = [damage - reduction, 0].max

    # Absorb with shields
    damage = StatusEffectService.absorb_damage_with_shields(target, damage, damage_type)

    damage
  end

  # Apply forced movement to target
  def apply_forced_movement(target, segment)
    return if target.hex_x.nil? || target.hex_y.nil?

    fm = ability.parsed_forced_movement
    direction = fm['direction']
    distance = fm['distance'].to_i

    case direction.to_s.downcase
    when 'away', 'push'
      return if actor.hex_x.nil? || actor.hex_y.nil?

      move_away_from_actor(target, distance)
    when 'toward', 'towards', 'pull'
      return if actor.hex_x.nil? || actor.hex_y.nil?

      move_toward_actor(target, distance)
    else
      # Specific direction (n, s, e, w, etc.)
      move_in_direction(target, direction, distance)
    end

    @events << create_event(segment, 'ability_forced_movement',
                            ability_name: ability.name,
                            direction: direction,
                            distance: distance,
                            target_id: target.id,
                            target_name: target.character_name,
                            new_x: target.hex_x,
                            new_y: target.hex_y)
  end

  # Move target away from actor
  def move_away_from_actor(target, distance)
    dx = target.hex_x - actor.hex_x
    dy = target.hex_y - actor.hex_y
    dist = Math.sqrt(dx * dx + dy * dy)
    return if dist == 0

    new_x = target.hex_x + (dx / dist * distance).round
    new_y = target.hex_y + (dy / dist * distance).round

    # Clamp to valid arena hex bounds
    new_x, new_y = clamp_to_arena_hex(new_x, new_y)

    target.update(hex_x: new_x, hex_y: new_y)
  end

  # Move target toward actor
  def move_toward_actor(target, distance)
    dx = actor.hex_x - target.hex_x
    dy = actor.hex_y - target.hex_y
    dist = Math.sqrt(dx * dx + dy * dy)
    return if dist == 0

    move_dist = [distance, dist].min
    new_x = target.hex_x + (dx / dist * move_dist).round
    new_y = target.hex_y + (dy / dist * move_dist).round

    # Clamp to valid arena hex bounds
    new_x, new_y = clamp_to_arena_hex(new_x, new_y)

    target.update(hex_x: new_x, hex_y: new_y)
  end

  # Move in a specific direction, stepping one hex at a time using hex grid math
  def move_in_direction(target, direction, distance)
    hex_dir = normalize_hex_direction(direction)
    return unless hex_dir

    current_x = target.hex_x
    current_y = target.hex_y

    distance.times do
      neighbor = HexGrid.hex_neighbor_by_direction(current_x, current_y, hex_dir)
      break unless neighbor

      nx, ny = neighbor
      nx, ny = clamp_to_arena_hex(nx, ny)
      current_x = nx
      current_y = ny
    end

    target.update(hex_x: current_x, hex_y: current_y)
  end

  # Map ability direction strings to hex grid directions (6-directional hex grid)
  # East/West are mapped to nearest hex directions (NE/SE and NW/SW respectively)
  def normalize_hex_direction(direction)
    case direction.to_s.downcase
    when 'n', 'north' then :n
    when 's', 'south' then :s
    when 'ne', 'northeast', 'e', 'east' then :ne
    when 'se', 'southeast' then :se
    when 'nw', 'northwest', 'w', 'west' then :nw
    when 'sw', 'southwest' then :sw
    end
  end

  # Apply prone status to target
  def apply_prone(target, segment)
    StatusEffectService.apply_by_name(
      participant: target,
      effect_name: 'prone',
      duration_rounds: 1,
      applied_by: actor
    )

    @events << create_event(segment, 'ability_knockdown',
                            ability_name: ability.name,
                            target_id: target.id,
                            target_name: target.character_name)
  end

  # Process healing to a target
  def process_healing(target, is_primary, segment)
    heal_amount = roll_damage # Same dice roll mechanism
    actual_heal = target.heal!(heal_amount)

    @events << create_event(segment, 'ability_heal',
                            ability_name: ability.name,
                            heal_amount: heal_amount,
                            actual_heal: actual_heal,
                            is_aoe: !is_primary,
                            target_id: target.id,
                            target_name: target.character_name,
                            new_hp: target.current_hp)
  end

  # Roll damage for the ability
  # For PCs: uses the unified 2d8+willpower roll passed as @base_roll
  # For NPCs: uses ability-specific dice or NPC custom dice
  def roll_damage
    # Use pre-rolled base if provided (unified PC roll)
    if @base_roll
      base = @base_roll[:total]
    elsif ability.base_damage_dice
      # Fall back to ability-specific dice (NPCs or legacy)
      base = DiceNotationService.roll(ability.base_damage_dice)
    else
      base = 0
    end

    # Apply ability damage modifier (flat +/-)
    modifier = ability.damage_modifier.to_i
    base += modifier

    # Apply dice-based damage modifier (+1d6, -1d4, etc.)
    if ability.respond_to?(:damage_modifier_dice) && !ability.damage_modifier_dice.to_s.strip.empty?
      base += ability.calculate_modifier_dice
    end

    # Apply ability damage multiplier (percentage, e.g., 1.5 = 150%)
    multiplier = ability.damage_multiplier.to_f
    if multiplier > 0 && multiplier != 1.0
      base = (base * multiplier).round
    end

    # Add stat modifier if configured
    stat_bonus = 0
    if ability.damage_stat
      stat_bonus = actor.stat_modifier(ability.damage_stat)
    end

    # If the round-level roll already includes all-roll penalties, only apply
    # ability-specific penalties here to avoid double counting.
    penalty = if @base_roll
                actor.ability_roll_penalty
              else
                actor.total_ability_penalty
              end

    total = [base + stat_bonus + penalty, 0].max

    # Apply timing coefficient if enabled for this ability
    # Earlier abilities (lower activation_segment) have lower coefficient, reducing power
    # This balances the timing advantage of abilities that activate early
    timing_coef = ability.effective_timing_coefficient
    if timing_coef < 1.0
      total = (total * timing_coef).round
    end

    total
  end

  # Apply status effects from ability configuration
  # For PCs with base_roll, duration scales with roll effectiveness
  def apply_status_effects(target, segment)
    ability.parsed_status_effects.each do |effect_config|
      # Support both 'effect' and 'effect_name' keys
      effect_name = effect_config['effect'] || effect_config['effect_name']
      next unless effect_name

      # Get base duration from config or ability defaults
      base_duration = effect_config['duration_rounds'] || effect_config['duration'] ||
                      ability.status_base_duration || 1

      # For PCs with unified roll, scale duration with roll effectiveness
      duration = if @base_roll
                   scaling = ability.status_duration_scaling || 10
                   bonus = (@base_roll[:total] / scaling).to_i
                   base_duration + bonus
                 else
                   base_duration
                 end

      value = effect_config['value']

      # Roll for chance-based effects (default 100% if no chance specified)
      chance = normalize_status_effect_chance(effect_config['chance'])
      roll = rand
      next if roll > chance

      # Check effect threshold - effect only applies if roll >= threshold
      # Used for binary effects (stun, etc.) that require a minimum roll
      effect_threshold = effect_config['effect_threshold']
      if effect_threshold && @base_roll
        next if @base_roll[:total] < effect_threshold.to_i
      end

      result = StatusEffectService.apply_by_name(
        participant: target,
        effect_name: effect_name,
        duration_rounds: duration,
        value: value,
        applied_by: actor
      )

      next unless result

      @events << create_event(segment, 'status_applied',
                              ability_name: ability.name,
                              effect_name: effect_name,
                              duration_rounds: duration,
                              value: value,
                              target_id: target.id,
                              target_name: target.character_name)
    end
  end

  # Apply ability costs to the caster
  def apply_costs!
    actor.apply_ability_costs!(ability)
  end

  def clamp_to_arena_hex(hex_x, hex_y)
    HexGrid.clamp_to_arena(hex_x, hex_y, fight.arena_width, fight.arena_height)
  end

  def normalize_status_effect_chance(value)
    chance = value.nil? ? 1.0 : value.to_f
    chance /= 100.0 if chance > 1.0
    chance.clamp(0.0, 1.0)
  end

  def damaging_ability?
    return true if ability.base_damage_dice
    return false unless @base_roll

    ability.combat?
  end

  def chain_target_allowed?(target, friendly_fire)
    return valid_target_for_ability?(target) unless friendly_fire

    if ability.target_type == 'enemy'
      target.id != actor.id
    else
      valid_target_for_ability?(target)
    end
  end

  # Create an event hash
  def create_event(segment, event_type, **details)
    {
      segment: segment,
      actor_id: actor.id,
      actor_name: actor.character_name,
      target_id: details[:target_id],
      target_name: details[:target_name],
      event_type: event_type,
      round: fight.round_number,
      details: details
    }
  end
end
