# frozen_string_literal: true
require 'vips'

# Pixel-level wall map operations for battlemap combat.
# Reads an RGB PNG mask generated by the battlemap pipeline where each pixel encodes:
#   Red   (255,0,0)   → wall   — blocks movement and LOS always
#   Green (0,255,0)   → door   — always passable for movement and transparent to LOS
#   Blue  (0,0,255)   → window — blocks movement; transparent to LOS
#   Black (0,0,0)     → floor  — always passable and transparent
#
# Instantiate via +WallMaskService.for_room(room)+ which returns nil if the room
# has no mask URL, allowing callers to fall back to hex-level logic.
class WallMaskService
  # RGB threshold: dominant channel > 128, others < 64
  DOMINANT_THRESHOLD = 128
  OTHER_THRESHOLD    = 64
  EDGE_CORRIDOR_HALF = 1   # sample 3 pixels wide at shared edge midpoint

  # Pixel type symbols
  FLOOR  = :floor
  WALL   = :wall
  DOOR   = :door
  WINDOW = :window

  # Fixed 6-direction offsets (N,NE,SE,S,SW,NW) — indexed to match passable_edges bits.
  # Do NOT use HexGrid.hex_neighbors here; it filters invalid coords.
  HEX_OFFSETS = [
    [0, 4],   # N  (bit 0)
    [1, 2],   # NE (bit 1)
    [1, -2],  # SE (bit 2)
    [0, -4],  # S  (bit 3)
    [-1, -2], # SW (bit 4)
    [-1, 2]   # NW (bit 5)
  ].freeze

  # Returns a WallMaskService instance for the room, or nil if the room has no mask URL.
  def self.for_room(room)
    return nil unless room.respond_to?(:battle_map_wall_mask_url) &&
                      !room.battle_map_wall_mask_url.to_s.strip.empty?
    new(room)
  end

  def initialize(room)
    @room = room
    @image = nil
    @load_attempted = false
    @pixel_cache = {}
    @hex_geometry = nil  # lazy-computed hex layout params
  end

  # Returns :wall, :door, :window, or :floor for a pixel coordinate.
  def pixel_type(px, py)
    load_image
    return FLOOR unless @image

    key = [px.clamp(0, @image.width - 1), py.clamp(0, @image.height - 1)]
    @pixel_cache[key] ||= classify_pixel(@image.getpoint(*key))
  rescue Vips::Error => e
    warn "[WallMaskService] getpoint error: #{e.message}"
    FLOOR
  end

  def wall_pixel?(px, py);   pixel_type(px, py) == WALL;   end
  def door_pixel?(px, py);   pixel_type(px, py) == DOOR;   end
  def window_pixel?(px, py); pixel_type(px, py) == WINDOW; end
  def floor_pixel?(px, py);  pixel_type(px, py) == FLOOR;  end

  # Pixel LOS ray from (x1,y1) to (x2,y2) in pixel coordinates.
  # +door_open_fn+: callable(pixel_x, pixel_y) → true if the door at this pixel is open.
  # Returns true if line of sight is clear.
  # Endpoints are skipped (character hex centers may have adjacent wall pixels).
  def ray_los_clear?(x1, y1, x2, y2, door_open_fn: nil)
    load_image
    return true unless @image

    each_line_pixel(x1, y1, x2, y2, skip_endpoints: true) do |px, py|
      case pixel_type(px, py)
      when WALL   then return false
      when WINDOW then next   # windows are transparent to LOS
      when DOOR
        is_open = door_open_fn ? door_open_fn.call(px, py) : false
        return false unless is_open
      end
    end
    true
  rescue StandardError => e
    warn "[WallMaskService] ray_los_clear? error: #{e.message}"
    true  # fail open
  end

  # Precompute passable_edges bitfield for a hex (called by pipeline).
  # Wall and window pixels block movement; door pixels treated as passable at precompute
  # time — runtime checks door state separately.
  def compute_passable_edges(hex_x, hex_y)
    load_image
    return 63 unless @image   # no mask = all edges passable

    result = 0
    HEX_OFFSETS.each_with_index do |(dx, dy), bit|
      nx = hex_x + dx
      ny = hex_y + dy
      result |= (1 << bit) if movement_edge_clear?(hex_x, hex_y, nx, ny)
    end
    result
  end

  # Convert hex coordinates to pixel coordinates using flat-top hex geometry.
  # Must match HexOverlayService#build_hex_pixel_map and the JS hexToPixel()
  # so that passable_edges and LOS rays sample the same mask pixels the editor
  # displays.
  def hex_to_pixel(hex_x, hex_y)
    g = hex_geometry
    col = hex_x - g[:min_x]
    visual_row = ((hex_y - g[:min_y]) / 4.0).floor
    visual_row = (g[:num_visual_rows] - 1) - visual_row  # Y-flip: north at top
    stagger = col.to_i.odd? ? -g[:hex_height] / 2.0 : 0

    px = (g[:hex_size] + col * g[:hex_size] * 1.5).round
    py = (g[:hex_height] / 2.0 + visual_row * g[:hex_height] + stagger).round
    [px.clamp(0, mask_width.to_i - 1), py.clamp(0, mask_height.to_i - 1)]
  end

  # Convert feet coordinates to pixel coordinates (linear mapping for non-hex callers).
  def feet_to_pixel(fx, fy)
    rw = (@room.max_x - @room.min_x).to_f
    rh = (@room.max_y - @room.min_y).to_f
    mw = mask_width.to_f
    mh = mask_height.to_f
    px = ((fx - @room.min_x) / rw * mw).round.clamp(0, mw.to_i - 1)
    py = ((fy - @room.min_y) / rh * mh).round.clamp(0, mh.to_i - 1)
    [px, py]
  end

  # Convert pixel coordinates back to feet (inverse of feet_to_pixel).
  def pixel_to_feet(px, py)
    rw = (@room.max_x - @room.min_x).to_f
    rh = (@room.max_y - @room.min_y).to_f
    fx = px.to_f / mask_width  * rw + @room.min_x
    fy = py.to_f / mask_height * rh + @room.min_y
    [fx, fy]
  end

  private

  # Lazily compute hex geometry params matching HexOverlayService#build_hex_pixel_map.
  # Cached per instance so compute_passable_edges loops don't recompute.
  def hex_geometry
    @hex_geometry ||= begin
      room_w = (@room.max_x - @room.min_x).to_f
      room_h = (@room.max_y - @room.min_y).to_f
      hex_coords = HexGrid.hex_coords_for_room(0, 0, room_w, room_h)

      all_xs = hex_coords.map { |x, _| x }
      all_ys = hex_coords.map { |_, y| y }
      min_x = all_xs.min || 0
      min_y = all_ys.min || 0
      num_cols = (all_xs.max || 0) - min_x
      num_visual_rows = (((all_ys.max || 0) - min_y) / 4.0).floor + 1

      mw = mask_width.to_f
      mh = mask_height.to_f
      hex_size_by_width  = mw / [num_cols * 1.5 + 2.0, 1].max
      hex_size_by_height = mh / [(num_visual_rows + 0.5) * Math.sqrt(3), 1].max
      hex_size = [hex_size_by_width, hex_size_by_height].max

      {
        min_x: min_x,
        min_y: min_y,
        num_visual_rows: num_visual_rows,
        hex_size: hex_size,
        hex_height: hex_size * Math.sqrt(3)
      }
    end
  end

  def mask_width
    @room.battle_map_wall_mask_width || @image&.width || 512
  end

  def mask_height
    @room.battle_map_wall_mask_height || @image&.height || 512
  end

  # Classify an RGB pixel array [r, g, b] into a feature type.
  def classify_pixel(bands)
    r = bands[0].to_i
    g = bands[1].to_i
    b = bands[2].to_i

    if r > DOMINANT_THRESHOLD && g < OTHER_THRESHOLD && b < OTHER_THRESHOLD
      WALL
    elsif g > DOMINANT_THRESHOLD && r < OTHER_THRESHOLD && b < OTHER_THRESHOLD
      DOOR
    elsif b > DOMINANT_THRESHOLD && r < OTHER_THRESHOLD && g < OTHER_THRESHOLD
      WINDOW
    else
      FLOOR
    end
  end

  # Check if the shared edge between two hexes is clear for movement.
  # Wall and window pixels block; door pixels do NOT block (door state checked at runtime).
  def movement_edge_clear?(from_x, from_y, to_x, to_y)
    fp = hex_to_pixel(from_x, from_y)
    tp = hex_to_pixel(to_x, to_y)

    # Trace a line from origin hex center to destination hex center.
    # If any pixel along the line (including the destination) is wall or window,
    # movement is blocked. Skip the origin — you're already standing there.
    each_line_pixel(fp[0], fp[1], tp[0], tp[1]) do |px, py|
      next if px == fp[0] && py == fp[1]  # skip origin
      t = pixel_type(px, py)
      return false if t == WALL || t == WINDOW
    end
    true
  end

  def load_image
    return if @image || @load_attempted

    @load_attempted = true
    url  = @room.battle_map_wall_mask_url
    path = resolve_path(url)
    return unless path

    img = Vips::Image.new_from_file(path)
    # Keep RGB (3 bands); strip alpha if present
    @image = img.bands >= 3 ? img.extract_band(0, n: 3) : img
  rescue Vips::Error => e
    warn "[WallMaskService] Load failed for room #{@room.id}: #{e.message}"
  end

  # Mirrors DynamicLightingService#resolve_battlemap_path
  def resolve_path(url)
    return nil if url.nil? || url.strip.empty? || !url.start_with?('/')

    path = File.expand_path(File.join('public', url))
    allowed = File.expand_path('public')
    return nil unless path.start_with?("#{allowed}/")

    File.exist?(path) ? path : nil
  end

  # Enumerate pixels along a line using Bresenham's algorithm.
  def each_line_pixel(x1, y1, x2, y2, skip_endpoints: false)
    dx = (x2 - x1).abs
    dy = (y2 - y1).abs
    sx = x1 < x2 ? 1 : -1
    sy = y1 < y2 ? 1 : -1
    err = dx - dy
    x, y = x1, y1
    total = [dx, dy].max
    idx = 0

    loop do
      yield [x, y] unless skip_endpoints && (idx == 0 || idx == total)
      break if x == x2 && y == y2

      e2 = 2 * err
      if e2 > -dy
        err -= dy
        x += sx
      end
      if e2 < dx
        err += dx
        y += sy
      end
      idx += 1
    end
  end
end
